return {
	other = {
		diff = "╱",
		indent = "│",
		column = "▏",
	},
	listchars = {
		tab = "  ",
		trail = "·",
		nbsp = "␣",
	},
	fold = {
		open = "",
		close = "",
		folded = "󰁂",
	},
	diagnostics = {
		error = " ",
		warn = " ",
		hint = " ",
		info = " ",
	},
	virtual_text = "■",
	git = {
		add = "┃",
		change = "┃",
		delete = "▁",
		topdelete = "▔",
		changedelete = "┇",
		untracked = "┇",
	},
	comments = {
		fix = " ",
		todo = " ",
		hack = " ",
		warn = " ",
		perf = "󰓅 ",
		note = " ",
		test = " ",
	},
	dap = {
		paused = "󰏥 ",
		breakpoint = " ",
		condition = "󰍶 ",
		rejected = "󱑙 ",
		log = " ",
	},
	dap_extra = {
		current = "󰬪 ",
	},
	dap_controls = {
		pause = "",
		play = "",
		step_into = "",
		step_over = " ",
		step_out = "",
		step_back = " ",
		run_last = " ",
		terminate = " ",
		disconnect = " ",
	},
	dashboard = {
		find = " ",
		explorer = " ",
		newfile = " ",
		oldfiles = " ",
		grep = " ",
		config = " ",
		exit = " ",
		loadtime = "󰔛 ",
		lastsession = " ",
	},
}
